routes/web.php
<?php

use App\Http\Controllers\ComputersController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaticController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [StaticController::class, 'index'])->name('home.index');

Route::get('/about', [StaticController::class, 'about'])->name('home.about');

Route::get('/contact', [StaticController::class, 'contact'])->name('home.contact');

Route::resource('computers', ComputersController::class);



// Route::get('/store', function (){
//     $filter = request('style');
//     if(isset($filter)){
//         return 'The viewing shows <span style="color: red">'.$filter.'</span>';
//     }
//     return 'The viewing shows <span style="color: red">All Products</span>';

// });

Route::get('/store/{category?}/{item?}', function ($category = null, $item = null){
    if(isset($category)){
        if(isset($item)){
            return "<h1>{$item}</h1>";
        }
        return '<h1>'.$category.'</h1>';
    }
    return '<h1>STORE</h1>';
});

resources/views/about.blade.php
@extends('layout')

@section('title')
  <title>Welcome To Laravel About</title>
@endsection

@section('content')
<div class="max-w-7xl mx-auto p-6 lg:p-8">
    <div class="flex justify-center">
        <h1> About me </h1>
    </div>

    <div class="ml-4 text-center text-sm text-gray-500 dark:text-gray-400">
        About details me
    </div>
</div>
@endsection

resources/views/contact.blade.php
@extends('layout')

@section('title')
  <title>Welcome To Laravel Contact</title>
@endsection

@section('content')
<div class="max-w-7xl mx-auto p-6 lg:p-8">
    <div class="flex justify-center">
        <h1> Contact me </h1>
    </div>

    <div class="ml-4 text-center text-sm text-gray-500 dark:text-gray-400">
        Contact details me
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @yield('title')

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{{url('css/styles.css')}}"/>
</head>

<body class="antialiased">

    <div class="relative py-4 px-6">
        <nav>
            <a href="{{route('home.index')}}">Home</a>
            <a href="{{route('home.about')}}">About</a>
            <a href="{{route('computers.index')}}">Computers</a>
            <a href="{{route('computers.create')}}">Create Computer</a>
            <a href="{{route('home.contact')}}">Contact</a>
        </nav>
    </div>

    <div class="relative sm:flex sm:justify-center sm:items-center min-h-screen bg-dots-darker bg-center bg-gray-100 dark:bg-dots-lighter dark:bg-gray-900 selection:bg-red-500 selection:text-white">
        @yield('content')
    </div>

</body>

</html>