routes/web.php
<?php

use App\Http\Controllers\ComputersController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaticController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [StaticController::class, 'index'])->name('home.index');

Route::get('/about', [StaticController::class, 'about'])->name('home.about');

Route::get('/contact', [StaticController::class, 'contact'])->name('home.contact');

Route::resource('computers', ComputersController::class);



// Route::get('/store', function (){
//     $filter = request('style');
//     if(isset($filter)){
//         return 'The viewing shows <span style="color: red">'.$filter.'</span>';
//     }
//     return 'The viewing shows <span style="color: red">All Products</span>';

// });

Route::get('/store/{category?}/{item?}', function ($category = null, $item = null){
    if(isset($category)){
        if(isset($item)){
            return "<h1>{$item}</h1>";
        }
        return '<h1>'.$category.'</h1>';
    }
    return '<h1>STORE</h1>';
});

app/Models/Computer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Computer extends Model
{
    use HasFactory;
     protected $fillable = [
        'name',
        'origin',
        'price',
    ];
}

app/Http/Controllers/Api/ComputerController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ComputerResource;
use App\Models\Computer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ComputerController extends Controller
{
    use ApiResponseTrait;
    public function index()
    {
        $computers = ComputerResource::collection(Computer::get());

        try {
            if ($computers === false) {
                return $this->ApiResponse([], "no computers", 404);
            } else {
                return $this->ApiResponse($computers, "Computers have been showing successfuly", 200);
            }
        } catch (\Throwable $th) {
            return $this->ApiResponse([], $th, 404);
        }
    }


    public function show($id)
    {
        $computer = Computer::find($id);

        try {
            if ($computer) {
                return $this->ApiResponse(new ComputerResource($computer), "Computer has been showing successfuly", 200);
            } else {
                return $this->ApiResponse(null, "this computer is not found", 404);
            }
        } catch (\Throwable $th) {
            return $this->ApiResponse([], $th, 404);
        }
    }

    public function store(Request $request)
    {
        $valid = Validator::make($request->all(), [
            'name' => ['required', 'max:15'],
            'origin' => ['required', 'max:30'],
            'price' => ['required', 'integer']
        ]);

        if ($valid->fails()) {
            return $this->ApiResponse(null, $valid->errors(), 400);
        }

        $computer = Computer::create($request->all());

        try {

            if ($computer) {
                return $this->ApiResponse(new ComputerResource($computer), "Computer has been craeting successfuly", 201);
            } else {
                return $this->ApiResponse(null, "There is a failure in the creating's operation", 400);
            }
        } catch (\Throwable $th) {
            return $this->ApiResponse(['message' => 'There is a wrong!'], $th, 404);
        }
    }

    public function update(Request $request, $id)
    {
        $valid = Validator::make($request->all(), [
            'name' => ['required', 'max:15'],
            'origin' => ['required', 'max:30'],
            'price' => ['required', 'integer']
        ]);

        if ($valid->fails()) {
            return $this->ApiResponse(null, $valid->errors(), 400);
        }

        $computer = Computer::find($id);
        if(!$computer){
            return $this->ApiResponse(null, "this computer is not found", 404);
        }

        $computer->update($request->all());

        try {

            if ($computer) {
                return $this->ApiResponse(new ComputerResource($computer), "Computer has been updating successfuly", 200);
            } else {
                return $this->ApiResponse(null, "There is a failure in the creating's operation", 400);
            }
        } catch (\Throwable $th) {
            return $this->ApiResponse(['message' => 'There is a wrong!'], $th, 404);
        }
    }

    public function destroy($id){

        $computer = Computer::find($id);

        if(!$computer){
            return $this-> apiResponse(null, "this computer is not found", 404);
        }

        $computer->delete($id);

        if($computer){
            return $this->apiResponse([], "Computer has been deleting successfully", 200);
        }
    }
}

app/Http/Controllers/ComputersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Computer;

class ComputersController extends Controller
{

    //Array of static data
    // private static function getStaticData()
    // {
    //     return [
    //         ['id' => 1, 'name' => 'LG', 'origin' => 'Koria'],
    //         ['id' => 2, 'name' => 'HP', 'origin' => 'USA'],
    //         ['id' => 3, 'name' => 'Siemens', 'origin' => 'Germany'],
    //         ['id' => 3, 'name' => 'Lenovo', 'origin' => 'France'],
    //     ];
    // }

    public function index()
    {
        return view('computers.index', [
            'computers' => Computer::all(),
        ]);
    }

    public function create()
    {
        return view('computers.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'computer-name' => 'required',
            'computer-origin' => 'required',
            'computer-price' => ['required', 'integer'],
        ]);

        $computer = new Computer();
        $computer->name = strip_tags($request->input('computer-name'));
        $computer->origin = strip_tags($request->input('computer-origin'));
        $computer->price = strip_tags($request->input('computer-price'));

        $computer->save();

        return redirect()->route('computers.index');
    }

    public function show(string $id)
    {
        //$computers = self::getStaticData();
        //$index = array_search($id, array_column($computers, 'id'));
        $computer = Computer::findOrFail($id);

        // if ($computer === false) {
        //     abort(404);
        // }

        return view('computers.show', [
            "computer" => $computer,
        ]);
    }

    public function edit(string $id)
    {
        return view('computers.edit', [
            'computer' => Computer::findOrFail($id),
        ]);
    }

    public function update(Request $request, string $id)
    {
        $request->validate([
            'computer-name' => 'required',
            'computer-origin' => 'required',
            'computer-price' => ['required', 'integer'],
        ]);

        $update_computer = Computer::findOrFail($id);
        $update_computer->name = strip_tags($request->input('computer-name'));
        $update_computer->origin = strip_tags($request->input('computer-origin'));
        $update_computer->price = strip_tags($request->input('computer-price'));

        $update_computer->save();

        return redirect()->route('computers.show', $id);
    }

   
    public function destroy(string $id)
    {
        $delete_computer = Computer::findOrFail($id);

        $delete_computer->delete();
        return redirect()->route('computers.index');
    }
}

resources/views/computers/create.blade.php
@extends('layout')

@section('title')
<title>Create Computers</title>
@endsection

@section('content')
<div class="max-w-7xl mx-auto">
    <div class="flex justify-center m-10">
        <h1> Create New a Computer </h1>
    </div>

    <div class="flex justify-center">
        <form action="{{route('computers.store')}}" , method="POST">
            @csrf
            <div>
                <label for="computer-name" class="text-sm">Computer Name</label>
                <input id="computer-name" name="computer-name" value="{{old('computer-name')}}" type="text">
                @error ('computer-name')
                   <div class="form-error">
                      {{$message}}
                   </div>
                @enderror
            </div>

            <div>
                <label for="computer-origin" class="text-sm">Computer Origin</label>
                <input id="computer-origin" , name="computer-origin" value="{{old('computer-origin')}}" type="text">
                @error ('computer-origin')
                   <div class="form-error">
                      {{$message}}
                   </div>
                @enderror
            </div>

            <div>
                <label for="computer-price" class="text-sm">Computer Price</label>
                <input id="computer-price" name="computer-price" value="{{old('computer-price')}}" type="text">
                @error ('computer-price')
                   <div class="form-error">
                      {{$message}}
                   </div>
                @enderror
            </div>

            <div>
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>

</div>
@endsection

resources/views/computers/edit.blade.php
@extends('layout')

@section('title')
<title>Edit Computers</title>
@endsection

@section('content')
<div class="max-w-7xl mx-auto">
    <div class="flex justify-center m-10">
        <h1> Edit An Old Computer </h1>
    </div>

    <div class="flex justify-center">
        <form action="{{route('computers.update', ['computer' => $computer->id ])}}" , method="POST">
            @csrf
            @method('PUT')
            <div>
                <label for="computer-name" class="text-sm">Computer Name</label>
                <input id="computer-name" name="computer-name" value="{{$computer->name}}" type="text">
                @error ('computer-name')
                   <div class="form-error">
                      {{$message}}
                   </div>
                @enderror
            </div>

            <div>
                <label for="computer-origin" class="text-sm">Computer Origin</label>
                <input id="computer-origin" , name="computer-origin" value="{{$computer->origin}}" type="text">
                @error ('computer-origin')
                   <div class="form-error">
                      {{$message}}
                   </div>
                @enderror
            </div>

            <div>
                <label for="computer-price" class="text-sm">Computer Price</label>
                <input id="computer-price" name="computer-price" value="{{$computer->price}}" type="text">
                @error ('computer-price')
                   <div class="form-error">
                      {{$message}}
                   </div>
                @enderror
            </div>

            <div>
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>

</div>
@endsection

resources/views/computers/index.blade.php
@extends('layout')

@section('title')
<title>Computers</title>
@endsection

@section('content')
<div class="max-w-7xl mx-auto p-6 lg:p-8">
    <div class="flex justify-center">
        <h1> Welcome Computers </h1>
    </div>

    <div class="ml-4 text-center text-sm text-gray-500 dark:text-gray-400">
        @if (count($computers) > 0)
        <ul>
            @foreach ($computers as $computer)
            <a href="{{route('computers.show', ['computer' => $computer['id']])}}">
                <li>
                    <p>
                        {{ $computer['name'] }} ( {{ $computer['origin'] }} ) - <strong>{{ $computer['price'] }}$</strong>
                    </p>
                </li>
            </a>
            @endforeach
        </ul>
        @else
        <p> THere are no computers to display </p>
        @endif
    </div>
</div>
@endsection

resources/views/computers/show.blade.php
@extends('layout')

@section('title')
<title>Show Computers</title>
@endsection

@section('content')
<div class="max-w-7xl mx-auto p-6 lg:p-8">
    <div class="flex justify-center">
        <h1> Welcome Computers </h1>
    </div>

    <div class="ml-4 text-center text-sm text-gray-500 dark:text-gray-400">

        <p>
        {{ $computer['name'] }} ( {{ $computer['origin'] }} ) - <strong>{{ $computer['price'] }}$</strong>
        </p>

    </div>

    <a class="edit-btn" href="{{route('computers.edit', $computer->id)}}">edit</a>

    <form  action="{{route('computers.destroy', $computer->id)}}" method="POST">
        @csrf
        @method('DELETE')
        
        <input class="delete-btn" type="submit" value="delete">
    </form>

</div>
@endsection